name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push, e.g., v1.0.0
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/test-and-build-plugin.yml
    secrets: inherit

  publish-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download all release artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: false

      - name: List downloaded artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.tar
            artifacts/**/*.msi
            artifacts/**/*.tar.gz
            artifacts/**/*.ez
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
